version: '3.8'

services:
  nanovm:
    build:
      context: .
      dockerfile: Dockerfile
    image: nanovm:${NANOVM_VERSION:-latest}
    container_name: nanovm
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8080}:8080"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./config:/etc/nanovm:ro
      - nanovm-data:/var/lib/nanovm
      - nanovm-logs:/var/log/nanovm
    environment:
      - RUST_LOG=${LOG_LEVEL:-info}
      - TZ=${TIMEZONE:-UTC}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-1}'
          memory: ${MEMORY_LIMIT:-512M}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
      - seccomp:seccomp-profile.json
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  # Optional monitoring stack components
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    depends_on:
      - nanovm
    restart: unless-stopped
    profiles: ['monitoring']

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    profiles: ['monitoring']

volumes:
  nanovm-data:
    driver: local
  nanovm-logs:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  default:
    name: nanovm-network
    driver: bridge 