[toolchain]
channel = "1.70.0"
components = ["rustfmt", "clippy", "rust-src", "rust-analysis", "miri"]
targets = [
    "x86_64-unknown-linux-gnu", 
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl"
]
profile = "minimal" 